### ISSUE TITLE
WS2801 LED strip

### ISSUE THREAD

**Issue by Goggite** [RaspiManu/MMM-FrameLight#2]
Hello!
It is difficult to find WS2801 LED strip for me.
Is there any similar Led strip which work with module?

**Comment by RaspiManu** [comment]
Dear @Goggite,

Thank you very much for your interest in our module.

### The answer to your question:
We developed the module to work with WS2801 LED strips because of the sound issues that some other LED strips could cause (see Readme). The communication with the strip works with [Adafruit CircuitPython WS2801](https://github.com/adafruit/Adafruit_CircuitPython_WS2801) which is only compatible with these LED strips as far as I know. Therefore I'm not able to recommend you another type of LED strip, although I did some research for you. If you have some advanced programming skills and want to add new LED options to the module, we are happy about a pull request.

### In case you want to do further research:
The closest type to WS2801 that I found within my research was the SK9822 LED type, but **you should definitely not just buy one and try it** instead of the WS2801 as there is a big risk of instantly killing your new LED strip or some connected components because of differences to WS2801. They even look very different. Please just use this as a starting point for you own web research.

Hopefully I was able to help you with your question.

Best wishes
RaspiManu

PS: I will keep this issue open for 2 day in case you want to answer.

**Comment by Goggite** [comment]
Dear RaspiManu,

Thank you for the information and for your time.
Unfortunately I dont have a good programming skills.
I will try to order WS2801, but the delivery will be long. So i will wait.

Thank you.
